### ISSUE TITLE
[Enhancement] A way for the tool to export it for "Projects for Obsidian"

### ISSUE THREAD

**Issue by zenminimalist** [rancoud/trello-json-to-markdown#1]
Idea:
Have the export format ready for non-kanban plugin format

I tried the [Projects for Obsidian](https://github.com/marcusolsson/obsidian-projects) plugin (which also has Kanban board view), but that seems to works a bit different and more inline with Obsidian "standards".

**Comment by rancoud** [comment]
Hello, if I understand how works [Projects for Obsidian](https://github.com/marcusolsson/obsidian-projects), it's a folder which each task is a note with a particular header to set the column's name on the board view.

Correct me if I'm wrong.

**Comment by zenminimalist** [comment]
It takes the data from frontmatter that is either in folders, tags or dataview queries

**Comment by rancoud** [comment]
I made a new Pull Request, I hope this answers your request.
